-- MySQL Script generated by MySQL Workbench
-- Fri Apr 15 20:52:00 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdexamen
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdexamen
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdexamen` DEFAULT CHARACTER SET utf8 ;
USE `bdexamen` ;

-- -----------------------------------------------------
-- Table `bdexamen`.`Grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Grupo` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `descripcion` VARCHAR(5) NULL,
  PRIMARY KEY (`idGrupo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Alumno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Alumno` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Alumno` (
  `idBoleta` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `appat` VARCHAR(45) NULL,
  `apmat` VARCHAR(45) NULL,
  `sexo` TINYINT(1) NULL,
  `edad` MEDIUMINT(2) NULL,
  `password` VARCHAR(45) NULL,
  `Grupo_idGrupo` INT NOT NULL,
  PRIMARY KEY (`idBoleta`, `Grupo_idGrupo`),
  INDEX `fk_Alumno_Grupo_idx` (`Grupo_idGrupo` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_Grupo`
    FOREIGN KEY (`Grupo_idGrupo`)
    REFERENCES `bdexamen`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Laboratorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Laboratorio` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Laboratorio` (
  `idLaboratorio` INT NOT NULL AUTO_INCREMENT,
  `tipo_lab` VARCHAR(45) NULL,
  PRIMARY KEY (`idLaboratorio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Monitor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Monitor` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Monitor` (
  `idMonitor` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMonitor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`CPU`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`CPU` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`CPU` (
  `idMaquina` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMaquina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Accesorios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Accesorios` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Accesorios` (
  `idAccesorios` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idAccesorios`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Configuracion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Configuracion` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Configuracion` (
  `idConfiguracion` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idConfiguracion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Marca` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Marca` (
  `idMarca` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idMarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Equipo` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Equipo` (
  `idEquipo` INT NOT NULL AUTO_INCREMENT,
  `Eitqueta` VARCHAR(45) NULL,
  `CPU_idMaquina` INT NOT NULL,
  `Monitor_idMonitor` INT NOT NULL,
  `Accesorios_idAccesorios` INT NOT NULL,
  `Configuracion_idConfiguracion` INT NOT NULL,
  `Laboratorio_idLaboratorio` INT NOT NULL,
  `Marca_idMarca` INT NOT NULL,
  PRIMARY KEY (`idEquipo`, `CPU_idMaquina`, `Monitor_idMonitor`, `Accesorios_idAccesorios`, `Configuracion_idConfiguracion`, `Laboratorio_idLaboratorio`, `Marca_idMarca`),
  INDEX `fk_Equipo_CPU1_idx` (`CPU_idMaquina` ASC) VISIBLE,
  INDEX `fk_Equipo_Monitor1_idx` (`Monitor_idMonitor` ASC) VISIBLE,
  INDEX `fk_Equipo_Accesorios1_idx` (`Accesorios_idAccesorios` ASC) VISIBLE,
  INDEX `fk_Equipo_Configuracion1_idx` (`Configuracion_idConfiguracion` ASC) VISIBLE,
  INDEX `fk_Equipo_Laboratorio1_idx` (`Laboratorio_idLaboratorio` ASC) VISIBLE,
  INDEX `fk_Equipo_Marca1_idx` (`Marca_idMarca` ASC) VISIBLE,
  CONSTRAINT `fk_Equipo_CPU1`
    FOREIGN KEY (`CPU_idMaquina`)
    REFERENCES `bdexamen`.`CPU` (`idMaquina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Monitor1`
    FOREIGN KEY (`Monitor_idMonitor`)
    REFERENCES `bdexamen`.`Monitor` (`idMonitor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Accesorios1`
    FOREIGN KEY (`Accesorios_idAccesorios`)
    REFERENCES `bdexamen`.`Accesorios` (`idAccesorios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Configuracion1`
    FOREIGN KEY (`Configuracion_idConfiguracion`)
    REFERENCES `bdexamen`.`Configuracion` (`idConfiguracion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Laboratorio1`
    FOREIGN KEY (`Laboratorio_idLaboratorio`)
    REFERENCES `bdexamen`.`Laboratorio` (`idLaboratorio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Equipo_Marca1`
    FOREIGN KEY (`Marca_idMarca`)
    REFERENCES `bdexamen`.`Marca` (`idMarca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Docente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Docente` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Docente` (
  `numero_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `appat` VARCHAR(45) NULL,
  `apmat` VARCHAR(45) NULL,
  `sexo` VARCHAR(45) NULL,
  `edad` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`numero_empleado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Prioridad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Prioridad` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Prioridad` (
  `idPrioridad` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idPrioridad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Asignatura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Asignatura` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Asignatura` (
  `idAsignatura` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`idAsignatura`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`EstadoReporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`EstadoReporte` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`EstadoReporte` (
  `idEstadoReporte` INT NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstadoReporte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Reporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Reporte` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Reporte` (
  `idReporte` INT NOT NULL,
  `fecha` VARCHAR(45) NULL,
  `hora` VARCHAR(45) NULL,
  `Equipo_idEquipo` INT NOT NULL,
  `Docente_numero_empleado` INT NOT NULL,
  `Alumno_idAlumno` INT NOT NULL,
  `Prioridad_idPrioridad` INT NOT NULL,
  `EstadoReporte_idEstadoReporte` INT NOT NULL,
  `Asignatura_idAsignatura` INT NOT NULL,
  `fecha_previa` VARCHAR(45) NULL,
  `hora_previa` VARCHAR(45) NULL,
  PRIMARY KEY (`idReporte`, `Equipo_idEquipo`, `Docente_numero_empleado`, `Alumno_idAlumno`, `Prioridad_idPrioridad`, `EstadoReporte_idEstadoReporte`, `Asignatura_idAsignatura`),
  INDEX `fk_Reporte_Equipo1_idx` (`Equipo_idEquipo` ASC) VISIBLE,
  INDEX `fk_Reporte_Docente1_idx` (`Docente_numero_empleado` ASC) VISIBLE,
  INDEX `fk_Reporte_Alumno1_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  INDEX `fk_Reporte_Prioridad1_idx` (`Prioridad_idPrioridad` ASC) VISIBLE,
  INDEX `fk_Reporte_EstadoReporte1_idx` (`EstadoReporte_idEstadoReporte` ASC) VISIBLE,
  INDEX `fk_Reporte_Asignatura1_idx` (`Asignatura_idAsignatura` ASC) VISIBLE,
  CONSTRAINT `fk_Reporte_Equipo1`
    FOREIGN KEY (`Equipo_idEquipo`)
    REFERENCES `bdexamen`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Docente1`
    FOREIGN KEY (`Docente_numero_empleado`)
    REFERENCES `bdexamen`.`Docente` (`numero_empleado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `bdexamen`.`Alumno` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Prioridad1`
    FOREIGN KEY (`Prioridad_idPrioridad`)
    REFERENCES `bdexamen`.`Prioridad` (`idPrioridad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_EstadoReporte1`
    FOREIGN KEY (`EstadoReporte_idEstadoReporte`)
    REFERENCES `bdexamen`.`EstadoReporte` (`idEstadoReporte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reporte_Asignatura1`
    FOREIGN KEY (`Asignatura_idAsignatura`)
    REFERENCES `bdexamen`.`Asignatura` (`idAsignatura`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdexamen`.`Alumno_has_Equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bdexamen`.`Alumno_has_Equipo` ;

CREATE TABLE IF NOT EXISTS `bdexamen`.`Alumno_has_Equipo` (
  `Alumno_idAlumno` INT NOT NULL,
  `Equipo_idEquipo` INT NOT NULL,
  `En uso` TINYINT(1) NULL,
  PRIMARY KEY (`Alumno_idAlumno`, `Equipo_idEquipo`),
  INDEX `fk_Alumno_has_Equipo_Equipo1_idx` (`Equipo_idEquipo` ASC) VISIBLE,
  INDEX `fk_Alumno_has_Equipo_Alumno1_idx` (`Alumno_idAlumno` ASC) VISIBLE,
  CONSTRAINT `fk_Alumno_has_Equipo_Alumno1`
    FOREIGN KEY (`Alumno_idAlumno`)
    REFERENCES `bdexamen`.`Alumno` (`idBoleta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Alumno_has_Equipo_Equipo1`
    FOREIGN KEY (`Equipo_idEquipo`)
    REFERENCES `bdexamen`.`Equipo` (`idEquipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
